version: '3'
services:
  rigolo-api:
    container_name: golang-rigolo-api
    build: .
    environment:
      - DB_USER=posoffline
      - DB_PASS=posofflinePassword
      - DB_NAME=in-the-middle
      - DB_HOST=in-the-middle-postgres
      - DB_PORT=5432
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - in-the-middle-postgres
    networks:
      - in-the-middle

  in-the-middle-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=posoffline
      - POSTGRES_PASSWORD=posofflinePassword
      - POSTGRES_DB=in-the-middle
      - DATABASE_HOST=in-the-middle-postgres
    ports:
      - '5432:5432'
    networks:
      - in-the-middle

networks:
  in-the-middle:
    driver: bridge